# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sz2Uyq04Jl1vYbWPiKt7hSBNUEKD_Xou
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Mount Google Drive (Optional if file is in Drive)
from google.colab import files

# Upload CSV file manually
uploaded = files.upload()

# Load the CSV file
file_name = "sales_data.csv"  # Make sure this matches the uploaded file
df = pd.read_csv(file_name)

# Display basic info and statistics
print("Dataset Info:\n", df.info())
print("\nDescriptive Statistics:\n", df.describe())

# Calculate the average of 'Sales'
average_sales = df["Sales"].mean()
print(f"\nAverage Sales: {average_sales}")

# Bar Chart: Total Sales per Product
plt.figure(figsize=(8,5))
df.groupby("Product")["Sales"].sum().plot(kind="bar", color='skyblue')
plt.title("Total Sales per Product")
plt.xlabel("Product")
plt.ylabel("Total Sales")
plt.show()

# Scatter Plot: Sales vs. Profit
plt.figure(figsize=(8,5))
plt.scatter(df["Sales"], df["Profit"], color='red', alpha=0.5)
plt.title("Sales vs. Profit")
plt.xlabel("Sales")
plt.ylabel("Profit")
plt.grid(True)
plt.show()

# Heatmap: Correlation Matrix
plt.figure(figsize=(6,5))
#sns.heatmap(df.corr(), annot=True, cmap="coolwarm", linewidths=0.5)
plt.title("Correlation Heatmap")
plt.show()